--- #YAML:1.0
name:               LaTeX-Driver
version:            0.10
abstract:           LaTeX Driver
author:
    - Andrew Ford <a.ford@ford-mason.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:   0
    Cwd:               0
    Exception::Class:  0
    File::Slurp:       0
    File::Spec:        0
    IO::File:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
